apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shopping-cart-ui
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: shopping-cart-ui
    spec:
      containers:
      - name: shopping-cart-ui
        image: registry.gitlab.com/dev-boot-camp/shopping-cart-starter/shopping-cart-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: shopping-cart-ui-registry
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-ui
  labels:
    app: shopping-cart-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: shopping-cart-ui
  type: LoadBalancer
