---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: shopping-cart-db
spec:
  ports:
    - port: 5432
  selector:
    app: shopping-cart-db
    tier: postgreSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: shopping-cart-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: shopping-cart-db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shopping-cart-db
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres@123
            - name: POSTGRES_DB
              value: shopping-cart
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim
